#!/bin/bash

tmp_img=$(mktemp /tmp/fzf-preview.XXXXXXXXXX)
tmp_ueberzug_file=""

if command -v ueberzug > /dev/null; then
    image_preview="ueberzug_preview"
    tmp_ueberzug_file=$(mktemp /tmp/fzf-ueberzug.XXXXXXXXXX)
    if command -v ueberzugpp > /dev/null; then
        tail -f --pid=$$ $tmp_ueberzug_file 2> /dev/null | ueberzugpp layer --silent &
    else
        tail -f --pid=$$ $tmp_ueberzug_file 2> /dev/null | ueberzug layer --silent &
    fi
elif [[ $KITTY_WINDOW_ID ]]; then
    image_preview="kitty_preview"
elif command -v chafa > /dev/null; then
    image_preview="chafa_preview"
elif command -v catimg > /dev/null; then
    image_preview="catimg_preview"
else
    image_preview="no_image_preview"
fi

cleanup () {
    if command -v ueberzug > /dev/null; then
        echo '{"action": "remove", "identifier": "fzf"}' >> $tmp_ueberzug_file
    fi
    rm -f $tmp_img $tmp_ueberzug_file
}
trap cleanup HUP

if command -v fd > /dev/null; then
    export FZF_DEFAULT_COMMAND='fd -H --type file'
fi

export FZF_DEFAULT_OPTS="\
--preview '$(dirname "$0")/fzf-file2preview.sh {} $image_preview $tmp_img $tmp_ueberzug_file' \
--bind 'resize:refresh-preview' --bind 'focus:transform-header:file --brief {}'"

FILE_PATH=$(echo "$(realpath "$(fzf)")")
URI="file://$FILE_PATH"

echo -n "$URI" | wl-copy --type text/uri-list

echo "Copied: $FILE_PATH"

cleanup
